import { onCall, HttpsError, CallableRequest } from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import { awardXp } from "./gamification";

const region = process.env.FIREBASE_REGION || "europe-west1";
const db = admin.firestore();

const MAX_MEMBERS = 8;

/** Simple alphanumeric invite code (6 chars). Not cryptographically secure — fine for MVP. */
function generateInviteCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

/**
 * Create a new family. Caller becomes creator, receives +300 XP + 300 points
 * (Season 0 family reward). Family ID is the doc ID auto-generated by Firestore.
 */
export const createFamily = onCall(
  { region },
  async (request: CallableRequest<{ name: string }>) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "Must be authenticated");
    }

    const userId = request.auth.uid;
    const { name } = request.data;

    if (!name || typeof name !== "string" || name.trim().length === 0 || name.trim().length > 60) {
      throw new HttpsError("invalid-argument", "Inserisci un nome per la famiglia (max 60 caratteri)");
    }

    const userRef = db.collection("users").doc(userId);
    const userSnap = await userRef.get();
    if (!userSnap.exists) {
      throw new HttpsError("not-found", "User not found");
    }

    // One-family enforcement: reject if already in a family.
    const existingFamilyId = userSnap.data()?.familyId;
    if (existingFamilyId && typeof existingFamilyId === "string" && existingFamilyId.trim() !== "") {
      throw new HttpsError("failed-precondition", "Sei già in una famiglia. Esci prima di crearne una nuova.");
    }

    const familyRef = await db.collection("families").add({
      name: name.trim(),
      createdBy: userId,
      memberCount: 1,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      settings: {
        allowTransfers: true,
        maxMembers: MAX_MEMBERS,
      },
    });

    const familyId = familyRef.id;
    const inviteCode = generateInviteCode();

    // Store invite code on the family doc (overwrite-safe; only creator sets it on creation).
    await familyRef.update({ inviteCode });

    // Award Season 0 family reward.
    const xpResult = await awardXp(userId, 300, "season0_family", `Famiglia "${name.trim()}" creata`);

    await userRef.update({
      familyId,
      familyRole: "creator",
      pointsBalance: admin.firestore.FieldValue.increment(300),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    // Points transaction ledger.
    const userSnapAfter = await userRef.get();
    await db.collection("users").doc(userId).collection("pointsTransactions").add({
      points: 300,
      type: "earned",
      source: "promotion",
      sourceId: "season0_family",
      description: `Famiglia "${name.trim()}" creata — reward Season 0`,
      balanceAfter: userSnapAfter.data()?.pointsBalance || 300,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    return {
      familyId,
      inviteCode,
      name: name.trim(),
      memberCount: 1,
      role: "creator",
      xpAwarded: 300,
      pointsAwarded: 300,
      xp: xpResult.xp,
      level: xpResult.level,
      xpToNextLevel: xpResult.xpToNextLevel,
    };
  },
);

/**
 * Join an existing family via invite code (or by familyId if already known).
 * Enforces one-family-per-user and max members cap.
 */
export const joinFamily = onCall(
  { region },
  async (request: CallableRequest<{ inviteCode?: string; familyId?: string }>) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "Must be authenticated");
    }

    const userId = request.auth.uid;
    const { inviteCode, familyId: familyIdOverrides } = request.data;

    const userRef = db.collection("users").doc(userId);
    const userSnap = await userRef.get();
    if (!userSnap.exists) {
      throw new HttpsError("not-found", "User not found");
    }

    // One-family enforcement.
    const existingFamilyId = userSnap.data()?.familyId;
    if (existingFamilyId && typeof existingFamilyId === "string" && existingFamilyId.trim() !== "") {
      throw new HttpsError("failed-precondition", "Sei già in una famiglia. Esci prima di entrarne un'altra.");
    }

    // Resolve family doc.
    let familyId = familyIdOverrides;
    if (!familyId) {
      if (!inviteCode || typeof inviteCode !== "string") {
        throw new HttpsError("invalid-argument", "Inserisci un codice invito o un familyId");
      }
      const familySnap = await db
        .collection("families")
        .where("inviteCode", "==", inviteCode.toUpperCase())
        .limit(1)
        .get();
      if (familySnap.empty) {
        throw new HttpsError("not-found", "Codice invito non trovato");
      }
      familyId = familySnap.docs[0].id;
    }

    const familyRef = db.collection("families").doc(familyId);
    const familySnap = await familyRef.get();
    if (!familySnap.exists) {
      throw new HttpsError("not-found", "Famiglia non trovata");
    }

    const familyData = familySnap.data() ?? {};
    const memberCount = typeof familyData.memberCount === "number" ? familyData.memberCount : 0;
    const maxMembers = familyData.settings?.maxMembers ?? MAX_MEMBERS;

    if (memberCount >= maxMembers) {
      throw new HttpsError("failed-precondition", "La famiglia è completa (raggiunto il massimo di membri)");
    }

    // Not the creator → join as member.
    const familyCreator = familyData.createdBy;
    if (familyCreator === userId) {
      throw new HttpsError("failed-precondition", "Sei già il creatore di questa famiglia");
    }

    await familyRef.update({
      memberCount: admin.firestore.FieldValue.increment(1),
    });

    await userRef.update({
      familyId,
      familyRole: "member",
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    return {
      familyId,
      inviteCode: familyData.inviteCode || null,
      name: familyData.name,
      memberCount: memberCount + 1,
      role: "member",
    };
  },
);

/**
 * Leave the current family. Creator cannot leave (must transfer or delete — P1).
 * Family doc memberCount is decremented; if it reaches 0 the doc is cleaned up.
 */
export const leaveFamily = onCall(
  { region },
  async (request: CallableRequest) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "Must be authenticated");
    }

    const userId = request.auth.uid;
    const userRef = db.collection("users").doc(userId);
    const userSnap = await userRef.get();
    if (!userSnap.exists) {
      throw new HttpsError("not-found", "User not found");
    }

    const familyId = userSnap.data()?.familyId;
    if (!familyId || typeof familyId !== "string" || familyId.trim() === "") {
      throw new HttpsError("failed-precondition", "Non sei in nessuna famiglia");
    }

    const familyRole = userSnap.data()?.familyRole;
    if (familyRole === "creator") {
      throw new HttpsError(
        "failed-precondition",
        "Il creatore non può uscire dalla famiglia. Trasferisci la proprietà prima (P1).",
      );
    }

    const familyRef = db.collection("families").doc(familyId);
    const familySnap = await familyRef.get();
    if (!familySnap.exists) {
      // Family doc missing — just clear user fields.
      await userRef.update({
        familyId: null,
        familyRole: null,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
      return { success: true, familyId, memberCount: 0 };
    }

    const memberCount = (familySnap.data()?.memberCount || 1) - 1;
    if (memberCount <= 0) {
      await familyRef.delete();
    } else {
      await familyRef.update({ memberCount });
    }

    await userRef.update({
      familyId: null,
      familyRole: null,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    return { success: true, familyId, memberCount };
  },
);

/**
 * Get the current user's family card (read-only).
 */
export const getMyFamily = onCall(
  { region },
  async (request: CallableRequest) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "Must be authenticated");
    }

    const userRef = db.collection("users").doc(request.auth.uid);
    const userSnap = await userRef.get();
    if (!userSnap.exists) {
      throw new HttpsError("not-found", "User not found");
    }

    const familyId = userSnap.data()?.familyId;
    if (!familyId || typeof familyId !== "string") {
      return { family: null };
    }

    const familySnap = await db.collection("families").doc(familyId).get();
    if (!familySnap.exists) {
      // Stale familyId — clear it.
      await userRef.update({ familyId: null, familyRole: null });
      return { family: null };
    }

    const data = familySnap.data() ?? {};
    const creatorSnap = await db.collection("users").doc(data.createdBy as string).get();
    const creatorName = creatorSnap.data()?.fullName || "Credente";
    const creatorAvatar = creatorSnap.data()?.avatarUrl || null;

    return {
      family: {
        id: familySnap.id,
        name: data.name,
        inviteCode: data.inviteCode || null,
        memberCount: data.memberCount || 0,
        createdBy: data.createdBy,
        creatorName,
        creatorAvatar,
        createdAt: data.createdAt?.toDate()?.toISOString() || null,
        settings: data.settings || null,
      },
    };
  },
);
